services:
  app:
    container_name: xxx_app
    build:
      context: .
      dockerfile: docker/app_php_ejemplo/php/Dockerfile
    image: app_php_ejemplo_php
    volumes:
      - ./app_php_ejemplo/src/:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 192.168.40.35
      DB_PORT: 3308
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: root
  db:
    container_name: xxx_db
    image: mysql:8.4
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: gym
      MYSQL_PASSWORD: 6SxifoRZKLHDvLyrx2y1
    ports:
      - "3308:3306"
  nginx:
    container_name: xxx_nginx
    image: nginx:alpine
    ports:
      - "8086:80"
    volumes:
      - ./docker/app_php_ejemplo/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/app_php_ejemplo/nginx/logs:/var/log/nginx
    depends_on:
      - app
  registry-server:
    container_name: xxx_docker_registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./docker/registry:/var/lib/registry
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.example.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'


  registry-ui:
    container_name: xxx_registry_ui
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8087:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000



volumes:
  dbdata:
  dockerregistry: